export default {
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTER_REQUESTED: 'REGISTER_REQUESTED',
    REGISTER_FAILED: 'REGISTER_REQUESTED',
    REGISTER_SUCCEEDED : 'REGISTER_SUCCEEDED',
    LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
    LOGOUT_SUCCEEDED: 'LOGOUT_SUCCEEDED',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    PLANNER_REQUESTED:'PLANNER_REQUESTED',
    PLANNER_SUCCEEDED:'PLANNER_SUCCEEDED',
    PLANNER_FAILED:'PLANNER_FAILED',
    UPDATE_COURSE_INPUTS: 'UPDATE_COURSE_INPUTS'
};