export default {
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
    LOGIN_FAILED: 'LOGIN_FAILED',

    REGISTER_REQUESTED: 'REGISTER_REQUESTED',
    REGISTER_SUCCEEDED: 'REGISTER_SUCCEEDED',
    REGISTER_FAILED: 'REGISTER_FAILED'
};